# PostgreSQL Config
spring.datasource.url=jdbc:postgresql://dpg-d9ok0pss728c73fanv70-a.oregon-postgres.render.com/donadoresyentidades_db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=donadoresyentidades_db_user
spring.datasource.password=MQWjTg6MnoEpYheC0YfyZmB5BAW1KN8X

# Enable H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA/Hibernate Configuration
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Actuator Configuration
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always

# DevTools Configuration
spring.devtools.restart.enabled=true

# Server Configuration for Dockerfile
server.port=${PORT:8080}

# Datadog

management.endpoint.prometheus.enabled=true
management.datadog.metrics.export.api-key=d1c6e117e3a2cbdf33b7b2a054f683d8
management.datadog.metrics.export.step=30s
management.datadog.metrics.export.enabled=true
management.datadog.metrics.export.uri=https://us5.datadoghq.com

\\